[profile.default]
src = "src"
out = "out"
libs = ["../lib"]
solc_version = "0.8.24"

remappings = [
    "@openzeppelin/=../lib/openzeppelin-contracts/",
    "@limitbreak/creator-token-standards/=../lib/creator-token-standards/",
    "forge-std/=../lib/openzeppelin-contracts/lib/forge-std/src/"
]

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }
